import { useEffect, useState } from "react";
import { Send, Sparkles } from "lucide-react";
import { apiFetch } from "../../services/api";
import PageHead from "../shared/PageHead";

export default function CareerAssistant() {
  const [sessions, setSessions] = useState<any[]>([]);
  const [active, setActive] = useState<any>(null);
  const [input, setInput] = useState("");
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState("");
  const starters = ["根据我的面试表现，制定下一周提升计划", "我的简历与目标岗位还有哪些差距？", "如何回答项目中最困难的问题？"];
  async function open(id: string) { const response = await apiFetch(`/api/career/${id}`, undefined, 10000); const result = await response.json(); if (response.ok) setActive(result.conversation); else setError(result.error); }
  async function load() { try { const response = await apiFetch("/api/career", undefined, 10000); const result = await response.json(); if (!response.ok) throw new Error(result.error || "无法读取咨询记录。"); setSessions(result.items || []); setError(""); if (!active && result.items?.length) await open(result.items[0].id); } catch (reason) { setError(reason instanceof Error ? reason.message : "无法读取咨询记录。"); } }
  useEffect(() => { void load(); }, []);
  async function create() { const response = await apiFetch("/api/career", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ title: "新的职业咨询" }) }, 10000); const result = await response.json(); if (response.ok) { setActive(result.conversation); await load(); } else setError(result.error); }
  async function send(text = input) { const value = text.trim(); if (!value || !active || loading) return; setLoading(true); setInput(""); setActive({ ...active, messages: [...(active.messages || []), { role: "user", content: value, source: "user" }] }); try { const response = await apiFetch(`/api/career/${active.id}/messages`, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ content: value }) }, 60000); const result = await response.json(); if (response.ok) { setActive(result.conversation); await load(); } else setActive((current: any) => ({ ...current, messages: [...(current.messages || []), { role: "assistant", content: result.error || "暂时无法回答。", source: "error" }] })); } finally { setLoading(false); } }
  async function remove(id: string) { if (!window.confirm("确定删除这段职业咨询吗？")) return; await apiFetch(`/api/career/${id}`, { method: "DELETE" }, 10000); if (active?.id === id) setActive(null); await load(); }
  return <div className="page page-career"><PageHead eyebrow="AI CAREER COACH" title="AI 职业助手" description="结合你的简历、面试报告、错题和训练计划，获得有上下文的求职建议。" />{error && <div className="admin-notice" role="alert">{error}</div>}<div className="career-layout"><aside className="panel career-sessions"><button className="primary career-new" onClick={create}>新建咨询</button><div className="career-session-list">{sessions.map(item => <div key={item.id} className={`career-session ${active?.id === item.id ? "active" : ""}`} onClick={() => open(item.id)}><button onClick={event => { event.stopPropagation(); void remove(item.id); }}>×</button><b>{item.title}</b><small>{item.message_count} 条消息 · {String(item.updated_at).slice(0, 16)}</small></div>)}</div></aside><section className="panel career-chat">{active ? <><header className="career-chat-head"><h3>{active.title}</h3><p>助手只依据你的项目数据提供建议，不会编造经历或承诺录用结果。</p></header><div className="career-messages">{(active.messages || []).map((message: any, index: number) => <div className={`career-message ${message.role}`} key={message.id || index}><span>{message.role === "user" ? "你" : "MOSS 职业教练"}</span><p>{message.content}</p>{message.role === "assistant" && <small className="career-source">{message.source === "spark" ? "讯飞星火" : "本地建议"}</small>}</div>)}{loading && <div className="career-message"><span>MOSS 职业教练</span><p>正在结合你的求职数据思考…</p></div>}</div><div className="career-starters">{starters.map(text => <button key={text} onClick={() => send(text)}>{text}</button>)}</div><div className="career-input"><textarea value={input} onChange={event => setInput(event.target.value)} onKeyDown={event => { if (event.key === "Enter" && !event.shiftKey) { event.preventDefault(); void send(); } }} placeholder="询问岗位选择、简历修改、面试策略或学习计划…" /><button className="primary" disabled={!input.trim() || loading} onClick={() => send()}><Send size={17} /></button></div></> : <div className="report-empty"><div><Sparkles size={28} /><p>新建一段咨询，开始制定你的求职策略。</p><button className="primary" onClick={create}>开始咨询</button></div></div>}</section></div></div>;
}
