import { useEffect, useState } from "react";
import { Area, AreaChart, CartesianGrid, ResponsiveContainer, Tooltip, XAxis, YAxis } from "recharts";
import { apiFetch } from "../../services/api";
import PageHead from "../shared/PageHead";

export default function AnalyticsDashboard() {
  const [data, setData] = useState<any>(null);
  const [error, setError] = useState("");
  async function load() { try { const response = await apiFetch("/api/admin/analytics", undefined, 10000); const result = await response.json(); if (!response.ok) throw new Error(result.error || "无法读取统计数据。"); setData(result); setError(""); } catch (reason) { setError(reason instanceof Error ? reason.message : "无法读取统计数据。"); } }
  useEffect(() => { void load(); }, []);
  if (!data) return <div className="page"><PageHead eyebrow="ANALYTICS" title="数据统计仪表盘" description={error || "正在汇总训练数据…"} /></div>;
  const cards = [["注册用户", data.summary.users, "人"], ["完成面试", data.summary.interviews, "次"], ["专项训练", data.summary.practices, "次"], ["平均得分", data.summary.average_score, "分"], ["星火出题率", data.summary.spark_rate, "%"], ["题库命中率", data.summary.bank_rate, "%"]];
  const maxWeak = Math.max(1, ...data.weak_skills.map((item: any) => item.count)); const maxRole = Math.max(1, ...data.roles.map((item: any) => item.n));
  return <div className="page page-analytics"><PageHead eyebrow="ADMIN ANALYTICS" title="训练数据总览" description="从现有匿名汇总记录观察产品使用、出题来源和能力短板。" /><section className="analytics-cards">{cards.map(card => <div className="panel" key={card[0]}><span>{card[0]}</span><strong>{card[1]}<small>{card[2]}</small></strong></div>)}</section><section className="analytics-grid"><div className="panel chart-panel"><div className="panel-title"><div><span>最近 14 天</span><h3>每日训练次数</h3></div><button className="secondary" onClick={load}>刷新</button></div><ResponsiveContainer width="100%" height={280}><AreaChart data={data.daily}><defs><linearGradient id="dailyTrain" x1="0" y1="0" x2="0" y2="1"><stop offset="0%" stopColor="#16a085" stopOpacity={.45} /><stop offset="100%" stopColor="#16a085" stopOpacity={0} /></linearGradient></defs><CartesianGrid strokeDasharray="4 4" stroke="#e6ebef" /><XAxis dataKey="date" tick={{ fontSize: 9 }} /><YAxis allowDecimals={false} /><Tooltip /><Area dataKey="count" name="训练次数" stroke="#16a085" fill="url(#dailyTrain)" strokeWidth={3} /></AreaChart></ResponsiveContainer></div><div className="panel metric-list"><div className="panel-title"><div><span>能力洞察</span><h3>常见薄弱能力</h3></div></div>{data.weak_skills.length ? data.weak_skills.map((item: any) => <div key={item.name}><span>{item.name}</span><i><em style={{ width: `${item.count * 100 / maxWeak}%` }} /></i><b>{item.count}</b></div>) : <div className="report-empty compact">暂无报告数据</div>}</div></section><section className="analytics-grid lower"><div className="panel metric-list"><div className="panel-title"><div><span>岗位分布</span><h3>热门训练岗位</h3></div></div>{data.roles.map((item: any) => <div key={item.role}><span>{item.role}</span><i><em style={{ width: `${item.n * 100 / maxRole}%` }} /></i><b>{item.n}</b></div>)}</div><div className="panel source-panel"><div className="panel-title"><div><span>出题来源</span><h3>模型与本地题库</h3></div></div>{data.sources.map((item: any) => <div key={item.name}><b>{item.name === "spark" ? "讯飞星火" : item.name === "question_bank" ? "本地题库" : item.name}</b><strong>{item.count}</strong></div>)}</div></section></div>;
}
