import { useEffect, useState, type FormEvent } from "react";
import { apiFetch } from "../../services/api";
import PageHead from "../shared/PageHead";

const empty = { category: "通用", interview_type: "技术面", difficulty: "中等", question: "", enabled: 1 };

export default function QuestionAdmin() {
  const [items, setItems] = useState<any[]>([]); const [form, setForm] = useState<any>(empty); const [editingId, setEditingId] = useState<number | null>(null); const [search, setSearch] = useState(""); const [csvText, setCsvText] = useState(""); const [notice, setNotice] = useState("");
  async function load(query = search) { const response = await apiFetch(`/api/admin/questions?search=${encodeURIComponent(query)}`, undefined, 10000); const result = await response.json(); if (!response.ok) throw new Error(result.error || "无法读取题库。"); setItems(result.items || []); }
  useEffect(() => { void load("").catch(reason => setNotice(reason.message)); }, []);
  async function save(event: FormEvent) { event.preventDefault(); setNotice(""); const response = await apiFetch(editingId ? `/api/admin/questions/${editingId}` : "/api/admin/questions", { method: editingId ? "PUT" : "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(form) }); const result = await response.json(); if (!response.ok) return setNotice(result.error || "保存失败。"); setForm(empty); setEditingId(null); setNotice("题目已保存。"); await load(); }
  async function remove(id: number) { if (!window.confirm("确定删除这道题吗？")) return; await apiFetch(`/api/admin/questions/${id}`, { method: "DELETE" }, 10000); await load(); }
  async function importCsv() { const response = await apiFetch("/api/admin/questions/import", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ csv_text: csvText }) }, 15000); const result = await response.json(); setNotice(`成功导入 ${result.imported || 0} 道题${result.errors?.length ? `，${result.errors.length} 行失败` : ""}`); setCsvText(""); await load(); }
  return <div className="page page-admin"><PageHead eyebrow="QUESTION BANK" title="题库管理后台" description="维护岗位分类、面试类型与题目难度，修改后立即用于本地题库出题。" /><section className="admin-grid"><form className="panel admin-form" onSubmit={save}><h3>{editingId ? "编辑题目" : "新增题目"}</h3><div className="two-col"><label>岗位分类<input value={form.category} onChange={event => setForm({ ...form, category: event.target.value })} /></label><label>面试类型<select value={form.interview_type} onChange={event => setForm({ ...form, interview_type: event.target.value })}><option>技术面</option><option>HR 面</option><option>综合面</option></select></label></div><label>难度<select value={form.difficulty} onChange={event => setForm({ ...form, difficulty: event.target.value })}><option>基础</option><option>中等</option><option>困难</option></select></label><label>题目<textarea rows={5} value={form.question} onChange={event => setForm({ ...form, question: event.target.value })} /></label><label className="admin-check"><input type="checkbox" checked={Boolean(form.enabled)} onChange={event => setForm({ ...form, enabled: event.target.checked ? 1 : 0 })} />启用题目</label><div className="admin-actions"><button className="primary">保存题目</button>{editingId && <button type="button" className="secondary" onClick={() => { setEditingId(null); setForm(empty); }}>取消</button>}</div></form><div className="panel import-panel"><h3>CSV 批量导入</h3><p>表头：category, interview_type, difficulty, question, enabled</p><textarea rows={9} value={csvText} onChange={event => setCsvText(event.target.value)} placeholder="category,interview_type,difficulty,question,enabled" /><button className="secondary" disabled={!csvText.trim()} onClick={importCsv}>导入 CSV</button>{notice && <div className="admin-notice" role="status">{notice}</div>}</div></section><section className="panel admin-table-panel"><div className="admin-search"><input value={search} onChange={event => setSearch(event.target.value)} placeholder="搜索题目或分类" /><button className="secondary" onClick={() => load().catch(reason => setNotice(reason.message))}>搜索</button><span>{items.length} 道题</span></div><div className="admin-table">{items.map(item => <div key={item.id} className={!item.enabled ? "disabled" : ""}><span><b>{item.category}</b><small>{item.interview_type} · {item.difficulty}</small></span><p>{item.question}</p><em>{item.enabled ? "启用" : "停用"}</em><button onClick={() => { setEditingId(item.id); setForm(item); window.scrollTo({ top: 0, behavior: "smooth" }); }}>编辑</button><button className="danger" onClick={() => remove(item.id)}>删除</button></div>)}</div></section></div>;
}
