import { useEffect, useState } from "react";
import { apiFetch } from "../../services/api";
import type { AuthUser } from "../auth/types";
import PageHead from "../shared/PageHead";

export default function SystemAdmin({ currentUser }: { currentUser: AuthUser }) {
  const [data, setData] = useState<any>(null);
  const [notice, setNotice] = useState("");
  async function load() { try { const response = await apiFetch("/api/admin/system", undefined, 10000); const result = await response.json(); if (!response.ok) throw new Error(result.error || "无法读取系统状态。"); setData(result); setNotice(""); } catch (reason) { setNotice(reason instanceof Error ? reason.message : "无法读取系统状态。"); } }
  useEffect(() => { void load(); }, []);
  async function toggle(key: string, value: boolean) { const response = await apiFetch("/api/admin/system/settings", { method: "PUT", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ [key]: value }) }); const result = await response.json(); if (response.ok) setData({ ...data, settings: result.settings }); else setNotice(result.error); }
  if (!data) return <div className="page"><PageHead eyebrow="SYSTEM" title="系统设置" description={notice || "正在读取系统状态…"} /></div>;
  return <div className="page page-system"><PageHead eyebrow="SYSTEM ADMIN" title="用户与模型服务" description="密钥不会显示在网页中；这里只提供配置状态、服务开关和失败记录。" /><section className="system-cards"><div className="panel service-card"><span>讯飞星火</span><b>{data.status.spark_configured ? "密钥已配置" : "密钥未配置"}</b><label><input type="checkbox" checked={data.settings.spark_enabled?.enabled} onChange={event => toggle("spark_enabled", event.target.checked)} />启用模型调用</label></div><div className="panel service-card"><span>本地 Whisper</span><b>模型：{data.status.whisper_model}</b><label><input type="checkbox" checked={data.settings.whisper_enabled?.enabled} onChange={event => toggle("whisper_enabled", event.target.checked)} />启用语音识别</label></div></section>{notice && <div className="admin-notice" role="alert">{notice}</div>}<section className="panel system-users"><div className="panel-title"><div><span>独立管理员数据库</span><h3>管理员账号</h3></div></div>{data.administrators.map((user: any) => <div key={user.id}><span><b>{user.name}</b><small>{user.email}{user.id === currentUser.id ? " · 当前管理员" : ""}</small></span><em>{user.active ? "启用" : "停用"}</em></div>)}</section><section className="panel system-users"><div className="panel-title"><div><span>普通用户数据库</span><h3>普通用户（只读）</h3></div></div>{data.users.map((user: any) => <div key={user.id}><span><b>{user.name}</b><small>{user.email}</small></span><em>普通用户</em></div>)}</section><section className="panel event-panel"><div className="panel-title"><div><span>运行记录</span><h3>最近模型失败日志</h3></div><button className="secondary" onClick={load}>刷新</button></div>{data.events.length ? data.events.map((event: any) => <div key={event.id}><b>{event.service}</b><span>{event.message}</span><small>{event.created_at}</small></div>) : <div className="report-empty compact">暂无失败记录</div>}</section></div>;
}
