import { useEffect, useState, type FormEvent } from "react";
import { BookOpen } from "lucide-react";
import { apiFetch } from "../../services/api";
import PageHead from "../shared/PageHead";

export default function ReviewNotes({ onOpenReport }: { onOpenReport: (item: any) => void }) {
  const [data, setData] = useState<any>({ items: [], interviews: [] });
  const [search, setSearch] = useState(""); const [sessionId, setSessionId] = useState(""); const [note, setNote] = useState(""); const [actions, setActions] = useState(""); const [tags, setTags] = useState(""); const [starred, setStarred] = useState(false); const [notice, setNotice] = useState("");
  async function load(query = search) { try { const response = await apiFetch(`/api/review-notes?search=${encodeURIComponent(query)}`, undefined, 10000); const result = await response.json(); if (!response.ok) throw new Error(result.error || "无法读取复盘笔记。"); setData(result); if (!sessionId && result.interviews?.length) setSessionId(result.interviews[0].id); } catch (reason) { setNotice(reason instanceof Error ? reason.message : "无法读取复盘笔记。"); } }
  useEffect(() => { void load(""); }, []);
  async function save(event: FormEvent) { event.preventDefault(); const response = await apiFetch(`/api/review-notes/${sessionId}`, { method: "PUT", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ note, actions: actions.split("\n"), tags: tags.replace("，", ",").split(","), starred }) }, 10000); const result = await response.json(); if (response.ok) { setNotice("复盘笔记已保存。"); setNote(""); setActions(""); setTags(""); setStarred(false); await load(); } else setNotice(result.error); }
  function edit(item: any) { setSessionId(item.session_id); setNote(item.note); setActions(item.actions.join("\n")); setTags(item.tags.join(",")); setStarred(item.starred); window.scrollTo({ top: 0, behavior: "smooth" }); }
  async function remove(id: number) { if (!window.confirm("确定删除这篇复盘笔记吗？")) return; await apiFetch(`/api/review-notes/${id}`, { method: "DELETE" }, 10000); await load(); }
  return <div className="page narrow page-review-notes"><PageHead eyebrow="INTERVIEW JOURNAL" title="面试复盘笔记" description="把面试报告整理成自己的经验库，记录反思、行动项和下一轮准备重点。" /><div className="review-notes-layout"><form className="panel review-note-form" onSubmit={save}><h3>编辑复盘笔记</h3><label>对应面试<select value={sessionId} onChange={event => setSessionId(event.target.value)}>{data.interviews.map((item: any) => <option value={item.id} key={item.id}>{String(item.completed_at || item.created_at).slice(0, 10)} · {item.role} · {item.score}分</option>)}</select></label><label>复盘内容<textarea value={note} onChange={event => setNote(event.target.value)} placeholder="这次回答哪里有效？哪里缺少证据？面试官可能还关注什么？" required /></label><label>行动项（每行一项）<textarea rows={4} value={actions} onChange={event => setActions(event.target.value)} placeholder={"补充项目量化指标\n重答系统设计问题"} /></label><label>标签（逗号分隔）<input value={tags} onChange={event => setTags(event.target.value)} placeholder="项目表达,系统设计,重点" /></label><label className="review-note-check"><input type="checkbox" checked={starred} onChange={event => setStarred(event.target.checked)} />标记为重点复盘</label><button className="primary" disabled={!sessionId}>保存笔记</button>{notice && <div className="profile-notice" role="status">{notice}</div>}</form><section><div className="review-note-search"><input value={search} onChange={event => setSearch(event.target.value)} onKeyDown={event => { if (event.key === "Enter") void load(); }} placeholder="搜索岗位、笔记或标签" /><button className="secondary" onClick={() => load()}>搜索</button></div><div className="review-note-list">{data.items.map((item: any) => <article className={`panel review-note-card ${item.starred ? "starred" : ""}`} key={item.id}><header><div><span className="eyebrow">{item.interview_type} · {String(item.completed_at).slice(0, 10)}{item.starred ? " · 重点" : ""}</span><h3>{item.role}</h3></div><strong>{item.score || 0} 分</strong></header><p>{item.note}</p><div className="review-note-tags">{item.tags.map((tag: string) => <span key={tag}>{tag}</span>)}</div>{item.actions.length > 0 && <ul className="review-note-actions-list">{item.actions.map((action: string) => <li key={action}>{action}</li>)}</ul>}<footer><button onClick={() => onOpenReport({ id: item.session_id, role: item.role })}>查看报告</button><button onClick={() => edit(item)}>编辑</button><button className="danger" onClick={() => remove(item.id)}>删除</button></footer></article>)}{!data.items.length && <div className="panel report-empty review-note-empty"><div><BookOpen size={28} /><p>暂无复盘笔记。完成面试后，在左侧选择记录并开始整理。</p></div></div>}</div></section></div></div>;
}
