import { useEffect, useState, type FormEvent, type ReactElement } from "react";
import { ArrowRight, Bot, ChevronLeft, Clock3, History, Sparkles, Target, TrendingUp } from "lucide-react";
import type { AuthUser } from "../auth/types";
import PageHead from "../shared/PageHead";

function Stat({ icon, label, value, unit, trend }: { icon: ReactElement; label: string; value: string; unit: string; trend: string }) { return <div className="stat-card"><div className="stat-icon">{icon}</div><div><span>{label}</span><strong>{value}<small>{unit}</small></strong><em>{trend}</em></div></div>; }
function HistoryRow({ date, role, score, type, duration_seconds, onOpen }: any) { const displayDate = /^\d{4}-\d{2}-\d{2}$/.test(date) ? new Date(`${date}T00:00:00`).toLocaleDateString("zh-CN", { month: "2-digit", day: "2-digit" }) : date; const minutes = Math.max(1, Math.round(Number(duration_seconds || 0) / 60)); return <div className="history-row" role="button" tabIndex={0} onClick={onOpen} onKeyDown={event => { if (event.key === "Enter" || event.key === " ") onOpen(); }}><div className="date-box">{displayDate}</div><div className="grow"><b>{role}</b><span>{type} · 约 {minutes} 分钟</span></div><div className="score-ring">{score}</div><ChevronLeft className="right-chevron" size={18} /></div>; }
function TrainingPlanCard({ data, onSave, onToggle, onStart }: any) { const [editing, setEditing] = useState(!data.plan); const [role, setRole] = useState(data.plan?.target_role || "多模态算法工程师"); const [target, setTarget] = useState(data.plan?.weekly_target || 3); const [skill, setSkill] = useState(data.plan?.focus_skill || "结构化表达"); const [error, setError] = useState(""); useEffect(() => { if (data.plan) { setRole(data.plan.target_role); setTarget(data.plan.weekly_target); setSkill(data.plan.focus_skill); } }, [data.plan]); const tasks = Array.isArray(data.tasks) ? data.tasks : []; const done = tasks.filter((task: any) => task.completed).length; async function submit(event: FormEvent) { event.preventDefault(); setError(""); try { await onSave({ target_role: role, weekly_target: Number(target), focus_skill: skill }); setEditing(false); } catch (reason) { setError(reason instanceof Error ? reason.message : "保存失败"); } } return <section className="panel training-plan-card"><div className="panel-title"><div><span>本周训练计划</span><h3>{data.plan ? `${data.plan.target_role} · ${done}/${tasks.length} 已完成` : "建立你的第一份训练计划"}</h3></div>{data.plan && <button className="text-btn" onClick={() => setEditing(!editing)}>{editing ? "收起" : "调整计划"}</button>}</div>{editing ? <form className="plan-form" onSubmit={submit}><label>目标岗位<input value={role} onChange={event => setRole(event.target.value)} required /></label><label>每周次数<select value={target} onChange={event => setTarget(Number(event.target.value))}>{[1, 2, 3, 4, 5, 6, 7].map(value => <option key={value} value={value}>{value} 次</option>)}</select></label><label>重点能力<input value={skill} onChange={event => setSkill(event.target.value)} required /></label><button className="primary">生成本周任务</button>{error && <div className="admin-notice">{error}</div>}</form> : <><div className="plan-progress"><i><em style={{ width: `${tasks.length ? done * 100 / tasks.length : 0}%` }} /></i><span>{tasks.length ? Math.round(done * 100 / tasks.length) : 0}%</span></div><div className="plan-task-list">{tasks.map((task: any) => <label key={task.id} className={task.completed ? "done" : ""}><input type="checkbox" checked={task.completed} onChange={event => onToggle(task.id, event.target.checked)} /><span><b>{task.title}</b><small>{task.description}</small></span>{!task.completed && <button type="button" onClick={onStart}>开始</button>}</label>)}</div></>}</section>; }

export default function HomeDashboard({ onStart, onShowAll, onOpenReport, history, user, trainingPlan, onSavePlan, onToggleTask }: { onStart: () => void; onShowAll: () => void; onOpenReport: (item: any) => void; history: any[]; user: AuthUser; trainingPlan: any; onSavePlan: (data: any) => Promise<void>; onToggleTask: (id: number, completed: boolean) => Promise<void> }) {
  return <div className="page page-home"><PageHead eyebrow={`你好，${user.name}`} title="准备好，让每次回答都更有分量。" description="基于你的目标岗位，完成一次有反馈、可复盘的沉浸式模拟面试。" /><section className="hero-card"><div className="hero-copy"><span className="pill"><Sparkles size={15} /> AI 个性化面试</span><h2>从简历出发，<br /><em>练到真正会表达。</em></h2><p>无需数字人视频。浏览器将通过自然语音、动态状态和实时字幕，构建专注、低干扰的面试体验。</p><button className="primary" onClick={onStart}>开始模拟面试 <ArrowRight size={18} /></button></div><div className="orb-stage"><div className="orbit orbit-one" /><div className="orbit orbit-two" /><div className="ai-orb"><Bot size={46} /><i /><i /><i /></div><div className="sound-bars">{[1, 2, 3, 4, 5, 6, 7].map(value => <span key={value} />)}</div><small>VOICE INTERVIEWER · READY</small></div></section><section className="stats-grid"><Stat icon={<Target />} label="综合能力" value="82" unit="/ 100" trend="+6 本月" /><Stat icon={<Clock3 />} label="累计训练" value="7.4" unit="小时" trend="超过 68% 用户" /><Stat icon={<TrendingUp />} label="连续提升" value="3" unit="次" trend="保持好状态" /></section><section className="split-grid"><div className="panel"><div className="panel-title"><div><span>最近训练</span><h3>把进步变成看得见的轨迹</h3></div><button className="text-btn" onClick={onShowAll}>查看全部</button></div><div className="history-list">{history.length ? history.slice(0, 3).map(item => <HistoryRow key={item.id} {...item} onOpen={() => onOpenReport(item)} />) : <div className="history-empty"><History size={22} /><span>完成第一次模拟面试后，训练记录会出现在这里。</span></div>}</div></div><div className="panel focus-panel"><span className="eyebrow">本周训练重点</span><h3>结构化表达</h3><p>你在技术细节上表现扎实，但结论通常出现得较晚。</p><div className="mini-path"><span className="done">1</span><i /><span className="done">2</span><i /><span>3</span></div><button className="secondary" onClick={onStart}>开始专项练习 <ArrowRight size={17} /></button></div></section><TrainingPlanCard data={trainingPlan} onSave={onSavePlan} onToggle={onToggleTask} onStart={onStart} /></div>;
}
